alias sshserver='ssh 192.168.0.200'
alias sshserverx='ssh -X 192.168.0.200'
alias sshida='ssh eripe320@remote-und.ida.liu.se'
alias sshidax='ssh -X eripe320@remote-und.ida.liu.se'
alias unrarall='unrar -r e *.rar'
alias vpn='sudo openvpn --config ~/.vpn/AzireVPN-SE.ovpn'
alias sysmonitor='cd ~/scripts && ./sensors.sh'
alias backupkeydb='mv /mnt/server/viktigt/db.kdbx /mnt/server/viktigt/olddb/db.kdbx.old && cp ~/KPDB2/db.kdbx /mnt/server/viktigt'
alias scan-image='sudo scanimage --mode Gray --resolution 300 > /storage/dokument/scan/raw/scan.tiff'
alias g++14='g++ -std=c++14 -Wall'
alias g++14debug='g++ -std=c++14 -Wall -g'
